# Generated by Django 4.1.6 on 2023-02-12 16:39

from django.db import migrations, models
import estagiodb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_Ter',
            fields=[
                ('uf', models.PositiveIntegerField(validators=[estagiodb.models.validar_uf])),
                ('nome_uf', models.CharField(max_length=30)),
                ('regiao_geografica_intermediaria', models.PositiveIntegerField(validators=[estagiodb.models.validar_regiao_geografica_intermediaria])),
                ('nome_regiao_geografica_intermediaria', models.CharField(max_length=100)),
                ('regiao_geografica_imediata', models.PositiveIntegerField(validators=[estagiodb.models.validar_regiao_geografica_imediata])),
                ('nome_regiao_geografica_imediata', models.CharField(max_length=100)),
                ('mesorregiao_geografica', models.PositiveIntegerField(validators=[estagiodb.models.validar_mesorregiao_geografica])),
                ('nome_mesorregiao', models.CharField(max_length=100)),
                ('microrregiao_geografica', models.PositiveIntegerField(validators=[estagiodb.models.validar_microrregiao_geografica])),
                ('nome_microrregiao', models.CharField(max_length=100)),
                ('municipio', models.PositiveIntegerField(validators=[estagiodb.models.validar_municipio])),
                ('codigo_municipio_completo', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, validators=[estagiodb.models.validar_codigo_municipio_completo])),
                ('nome_municipio', models.CharField(max_length=100)),
                ('codigo_municipio_6_digitos', models.PositiveIntegerField(validators=[estagiodb.models.validar_codigo_municipio_6_digitos])),
            ],
        ),
    ]
