# Generated by Django 4.1.6 on 2023-02-12 16:42

from django.db import migrations, models
import django.db.models.deletion
import estagiodb.models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiodb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(max_length=250)),
                ('grupo', models.CharField(max_length=250)),
                ('acao_detalhada', models.TextField()),
                ('competencia_parcela', models.CharField(max_length=250)),
                ('numero_ob', models.PositiveIntegerField(validators=[estagiodb.models.validar_numero_ob])),
                ('data_ob', models.DateField()),
                ('banco_ob', models.PositiveIntegerField(validators=[estagiodb.models.validar_banco_ob])),
                ('agencia_ob', models.PositiveIntegerField(validators=[estagiodb.models.validar_agencia_ob])),
                ('conta_ob', models.PositiveIntegerField(validators=[estagiodb.models.validar_conta_ob])),
                ('valor_total', models.FloatField()),
                ('desconto', models.FloatField()),
                ('valor_liquido', models.FloatField()),
                ('observacao', models.TextField()),
                ('processo', models.PositiveBigIntegerField()),
                ('tipo_repasse', models.CharField(max_length=250)),
                ('numero_proposta', models.PositiveIntegerField()),
                ('ibge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estagiodb.reg_ter', validators=[estagiodb.models.validar_ibge])),
            ],
        ),
    ]
